spring.application.name=Sprint

spring.datasource.url=jdbc:postgresql://localhost:5433/Sprint_DB
spring.datasource.username=Sprint_user
spring.datasource.password=Sprint_pass
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}